#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize_home_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the home filesystem to fill partition
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting resize_home_once"
    btrfs filesystem resize max /home &&
    update-rc.d resize_home_once remove &&
    rm /etc/init.d/resize_home_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
