#!/bin/bash -e

echo "Update mime database"
sudo mount -o remount,rw /
sudo update-mime-database /usr/share/mime
sudo mkdir /var/lib/dosecalibrator
sudo touch /var/lib/dosecalibrator/firstboot
sudo mount -o remount,ro /